name: publish container images
on:
  push:
    tags: ["v*"]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: checkout docker repository
        uses: actions/checkout@v2
        with:
          path: docker-repo

      - name: checkout NodeBB repository
        uses: actions/checkout@v2
        with:
          repository: NodeBB/NodeBB
          ref: ${GITHUB_REF}
      
      - uses: docker/setup-buildx-action@v1

      - name: Login in to docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login in to quay.io registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build container image and publish
        run: |
          cp docker-repo/Dockerfile .
          cp docker-repo/scripts/publish_container_images.sh ./publish_container_images.sh
          chmod +x ./publish_container_images.sh
          ./publish_container_images.sh
